# Generated by Django 2.1.4 on 2018-12-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20181221_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDImage',
            field=models.ImageField(blank=True, null=True, upload_to='prodcut/', verbose_name='Image'),
        ),
    ]
